name: Workflow with multiple stage

on: push

jobs:
  job-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: date
  job-on-windows:
    name: a windows job
    runs-on: windows-latest
    steps:
      - name: first step in windows job
        run: date
  job-on-macos:
    needs: [job-on-ubuntu, job-on-windows]
    runs-on: macos-latest
    name: a job that runs on mac after two jobs
    steps:
      - run: owd
      - name: new step
        run: ls
      - name: third step
        run: env
  final-job:
    needs: job-on-macos
    runs-on: ubuntu-latest
    name: a final job
    steps:
      - run: echo Hello World!
